FROM mcr.microsoft.com/dotnet/sdk:9.0.102-alpine3.21

WORKDIR /app

COPY . . 

ENV KESTREL__ENDPOINTS__HTTP__URL=http://+:80

EXPOSE 80
RUN dotnet tool install --global dotnet-ef
ENTRYPOINT ["dotnet", "watch", "--non-interactive"]